# This is a basic workflow to help you get started with Actions

name: Scan Docker image for vulnerabilities

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
 scan:
  runs-on: ubuntu-latest
  steps: 
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Scan Docker image for vulnerabilties
    uses: snyk/scanner@v1
    with:
      image: solomon1996-1/github-practice/python-dockerfile
  
